import { Offer } from '../models/Offer';

export const OFFERS: Offer[] = [
  {
    id: 11,
    pairName: 'Serena Williams - Simon Halep',
    option1: '1.30',
    optionX: '-',
    option2: '2.80',
    optionX1: '-',
    optionX2: '-',
    option12: '-',
    special: false,
    specialOption1: '-',
    specialOptionX: '-',
    specialOption2: '-',
    specialOptionX1: '-',
    specialOptionX2: '-',
    specialOption12: '-',
    option1Selected: false,
    optionXSelected: false,
    option2Selected: false,
    optionX1Selected: false,
    optionX2Selected: false,
    option12Selected: false,
    specialOption1Selected: false,
    specialOptionXSelected: false,
    specialOption2Selected: false,
    specialOptionX1Selected: false,
    specialOptionX2Selected: false,
    specialOption12Selected: false
  },
  {
    id: 12,
    pairName: 'Marin Čilić - Fernando Vedrasco',
    option1: '1.65',
    optionX: '-',
    option2: '2.40',
    optionX1: '-',
    optionX2: '-',
    option12: '-',
    special: false,
    specialOption1: '-',
    specialOptionX: '-',
    specialOption2: '-',
    specialOptionX1: '-',
    specialOptionX2: '-',
    specialOption12: '-',
    option1Selected: false,
    optionXSelected: false,
    option2Selected: false,
    optionX1Selected: false,
    optionX2Selected: false,
    option12Selected: false,
    specialOption1Selected: false,
    specialOptionXSelected: false,
    specialOption2Selected: false,
    specialOptionX1Selected: false,
    specialOptionX2Selected: false,
    specialOption12Selected: false
  },
  {
    id: 13,
    pairName: 'Hajduk - Dinamo',
    option1: '2.10',
    optionX: '3.00',
    option2: '1.70',
    optionX1: '1.90',
    optionX2: '1.30',
    option12: '1.10',
    special: true,
    specialOption1: '2.15',
    specialOptionX: '3.10',
    specialOption2: '1.95',
    specialOptionX1: '1.95',
    specialOptionX2: '1.45',
    specialOption12: '1.25',
    option1Selected: false,
    optionXSelected: false,
    option2Selected: false,
    optionX1Selected: false,
    optionX2Selected: false,
    option12Selected: false,
    specialOption1Selected: false,
    specialOptionXSelected: false,
    specialOption2Selected: false,
    specialOptionX1Selected: false,
    specialOptionX2Selected: false,
    specialOption12Selected: false
  },
  {
    id: 14,
    pairName: 'Osijek - Rijeka',
    option1: '2.10',
    optionX: '2.50',
    option2: '1.70',
    optionX1: '1.85',
    optionX2: '1.45',
    option12: '1.20',
    special: true,
    specialOption1: '2.20',
    specialOptionX: '3.00',
    specialOption2: '1.80',
    specialOptionX1: '1.95',
    specialOptionX2: '1.50',
    specialOption12: '1.35',
    option1Selected: false,
    optionXSelected: false,
    option2Selected: false,
    optionX1Selected: false,
    optionX2Selected: false,
    option12Selected: false,
    specialOption1Selected: false,
    specialOptionXSelected: false,
    specialOption2Selected: false,
    specialOptionX1Selected: false,
    specialOptionX2Selected: false,
    specialOption12Selected: false
  },
  {
    id: 15,
    pairName: 'Istra - Slaven Belupo',
    option1: '2.25',
    optionX: '4.00',
    option2: '1.65',
    optionX1: '1.95',
    optionX2: '1.35',
    option12: '1.35',
    special: true,
    specialOption1: '2.30',
    specialOptionX: '5.00',
    specialOption2: '2.10',
    specialOptionX1: '2.00',
    specialOptionX2: '1.40',
    specialOption12: '1.15',
    option1Selected: false,
    optionXSelected: false,
    option2Selected: false,
    optionX1Selected: false,
    optionX2Selected: false,
    option12Selected: false,
    specialOption1Selected: false,
    specialOptionXSelected: false,
    specialOption2Selected: false,
    specialOptionX1Selected: false,
    specialOptionX2Selected: false,
    specialOption12Selected: false
  }
];
